spring.application.name=aura-tap-query-service
server.port=8081

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/aura_db

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.marriott.aura=DEBUG
logging.level.org.springframework.data.mongodb=INFO
